version: "3"
services:
  app:
    container_name: octacat-app
    build:
      context: .
      dockerfile: Dockerfile
    command: 
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    networks:
      - octacat-networks
    depends_on:
      - storage
  storage:
    image: minio/minio:latest
    container_name: octacat-storage
    networks:
      - octacat-networks
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_user
    volumes:
      - "~/.cache/storage:/files"
    entrypoint: "minio server /files --console-address ':9001'"
  db:
    image: postgres:15-alpine
    container_name: octacat-db
    networks:
      - octacat-networks
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=octacat_db

networks:
  octacat-networks: {}