# fly.toml app configuration file generated for octacat-app-backend on 2023-09-29T22:12:30+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "octacat-app-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
