// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package psql

import (
	"database/sql"
	"time"
)

type Chat struct {
	ID         string
	FromUserID string
	ToUserID   string
	MessageID  string
	CreatedAt  time.Time
	CreatedBy  string
	UpdatedAt  sql.NullTime
	UpdatedBy  sql.NullString
	DeletedAt  sql.NullTime
	DeletedBy  sql.NullString
	IsDeleted  bool
}

type User struct {
	ID           string
	Name         string
	Email        string
	Password     string
	ProfileImage string
	CreatedAt    time.Time
	CreatedBy    string
	UpdatedAt    sql.NullTime
	UpdatedBy    sql.NullString
	DeletedAt    sql.NullTime
	DeletedBy    sql.NullString
	IsDeleted    bool
}
