name: Test before deploy
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18.0"
      - run: go test ./...
